name: Extract RootFS from Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull Docker Image
        run: |
          echo "Pulling spa5k/arch image"
          docker pull spa5k/arch:latest

      - name: Extract RootFS
        run: |
          docker create --name arch spa5k/arch echo "Arch Linux"
          docker export -o rootfs.tar arch
          gzip rootfs.tar
          docker rm arch

      - name: Upload RootFS
        uses: actions/upload-artifact@v4
        with:
          name: rootfs
          path: rootfs.tar.gz

  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download RootFS
        uses: actions/download-artifact@v4
        with:
          name: rootfs
          path: rootfs

      - name: List Files
        run: ls -R rootfs

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            rootfs/*.tar.gz
