name: Build, Push Docker Image and Extract RootFS

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract current date and time
        id: date
        run: echo "DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/arch:latest
            ${{ secrets.DOCKER_USERNAME }}/arch:${{ env.DATE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract RootFS
        run: |
          docker create --name arch ${{ secrets.DOCKER_USERNAME }}/arch:latest echo "Arch Linux"
          docker export -o rootfs.tar arch
          gzip rootfs.tar
          docker rm arch

      - name: Upload RootFS
        uses: actions/upload-artifact@v4
        with:
          name: rootfs
          path: rootfs.tar.gz

      - name: Download RootFS
        uses: actions/download-artifact@v4
        with:
          name: rootfs
          path: rootfs

      - name: List Files
        run: ls -R rootfs

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          tag_name: ${{ env.DATE }}
          release_name: ${{ env.DATE }}
          files: |
            rootfs/*.tar.gz
